#!/bin/bash

curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-BlackItalic.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-Black.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-BoldItalic.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-Bold.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-CondensedBlackItalic.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-CondensedBlack.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-CondensedBoldItalic.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-CondensedBold.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-CondensedExtraBoldItalic.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-CondensedExtraBold.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-CondensedExtraLightItalic.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-CondensedExtraLight.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-CondensedItalic.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-CondensedLightItalic.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-CondensedLight.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-CondensedMediumItalic.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-CondensedMedium.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-CondensedSemiBoldItalic.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-CondensedSemiBold.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-CondensedThinItalic.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-CondensedThin.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-Condensed.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-ExtraBoldItalic.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-ExtraBold.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-ExtraCondensedBlackItalic.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-ExtraCondensedBlack.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-ExtraCondensedBoldItalic.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-ExtraCondensedBold.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-ExtraCondensedExtraBoldItalic.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-ExtraCondensedExtraBold.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-ExtraCondensedExtraLightItalic.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-ExtraCondensedExtraLight.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-ExtraCondensedItalic.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-ExtraCondensedLightItalic.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-ExtraCondensedLight.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-ExtraCondensedMediumItalic.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-ExtraCondensedMedium.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-ExtraCondensedSemiBoldItalic.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-ExtraCondensedSemiBold.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-ExtraCondensedThinItalic.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-ExtraCondensedThin.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-ExtraCondensed.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-ExtraLightItalic.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-ExtraLight.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-Italic.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-LightItalic.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-Light.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-MediumItalic.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-Medium.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-Regular.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-SemiBoldItalic.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-SemiBold.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-SemiCondensedBlackItalic.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-SemiCondensedBlack.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-SemiCondensedBoldItalic.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-SemiCondensedBold.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-SemiCondensedExtraBoldItalic.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-SemiCondensedExtraBold.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-SemiCondensedExtraLightItalic.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-SemiCondensedExtraLight.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-SemiCondensedItalic.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-SemiCondensedLightItalic.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-SemiCondensedLight.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-SemiCondensedMediumItalic.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-SemiCondensedMedium.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-SemiCondensedSemiBoldItalic.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-SemiCondensedSemiBold.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-SemiCondensedThinItalic.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-SemiCondensedThin.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-SemiCondensed.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-ThinItalic.ttf
curl -s -O --output-dir lib/internal/NotoSans/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSans/full/ttf/NotoSans-Thin.ttf

curl -s -O --output-dir lib/internal/NotoSans-cjk/ --clobber https://raw.githubusercontent.com/notofonts/noto-cjk/refs/heads/main/Sans/Variable/TTF/NotoSansCJKhk-VF.ttf
curl -s -O --output-dir lib/internal/NotoSans-cjk/ --clobber https://raw.githubusercontent.com/notofonts/noto-cjk/refs/heads/main/Sans/Variable/TTF/NotoSansCJKjp-VF.ttf
curl -s -O --output-dir lib/internal/NotoSans-cjk/ --clobber https://raw.githubusercontent.com/notofonts/noto-cjk/refs/heads/main/Sans/Variable/TTF/NotoSansCJKkr-VF.ttf
curl -s -O --output-dir lib/internal/NotoSans-cjk/ --clobber https://raw.githubusercontent.com/notofonts/noto-cjk/refs/heads/main/Sans/Variable/TTF/NotoSansCJKsc-VF.ttf
curl -s -O --output-dir lib/internal/NotoSans-cjk/ --clobber https://raw.githubusercontent.com/notofonts/noto-cjk/refs/heads/main/Sans/Variable/TTF/NotoSansCJKtc-VF.ttf

curl -s -O --output-dir lib/internal/NotoSans-arabic/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSansArabic/full/ttf/NotoSansArabic-Black.ttf
curl -s -O --output-dir lib/internal/NotoSans-arabic/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSansArabic/full/ttf/NotoSansArabic-Bold.ttf
curl -s -O --output-dir lib/internal/NotoSans-arabic/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSansArabic/full/ttf/NotoSansArabic-CondensedBlack.ttf
curl -s -O --output-dir lib/internal/NotoSans-arabic/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSansArabic/full/ttf/NotoSansArabic-CondensedBold.ttf
curl -s -O --output-dir lib/internal/NotoSans-arabic/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSansArabic/full/ttf/NotoSansArabic-CondensedExtraBold.ttf
curl -s -O --output-dir lib/internal/NotoSans-arabic/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSansArabic/full/ttf/NotoSansArabic-CondensedExtraLight.ttf
curl -s -O --output-dir lib/internal/NotoSans-arabic/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSansArabic/full/ttf/NotoSansArabic-CondensedLight.ttf
curl -s -O --output-dir lib/internal/NotoSans-arabic/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSansArabic/full/ttf/NotoSansArabic-CondensedMedium.ttf
curl -s -O --output-dir lib/internal/NotoSans-arabic/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSansArabic/full/ttf/NotoSansArabic-CondensedSemiBold.ttf
curl -s -O --output-dir lib/internal/NotoSans-arabic/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSansArabic/full/ttf/NotoSansArabic-CondensedThin.ttf
curl -s -O --output-dir lib/internal/NotoSans-arabic/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSansArabic/full/ttf/NotoSansArabic-Condensed.ttf
curl -s -O --output-dir lib/internal/NotoSans-arabic/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSansArabic/full/ttf/NotoSansArabic-ExtraBold.ttf
curl -s -O --output-dir lib/internal/NotoSans-arabic/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSansArabic/full/ttf/NotoSansArabic-ExtraCondensedBlack.ttf
curl -s -O --output-dir lib/internal/NotoSans-arabic/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSansArabic/full/ttf/NotoSansArabic-ExtraCondensedBold.ttf
curl -s -O --output-dir lib/internal/NotoSans-arabic/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSansArabic/full/ttf/NotoSansArabic-ExtraCondensedExtraBold.ttf
curl -s -O --output-dir lib/internal/NotoSans-arabic/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSansArabic/full/ttf/NotoSansArabic-ExtraCondensedExtraLight.ttf
curl -s -O --output-dir lib/internal/NotoSans-arabic/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSansArabic/full/ttf/NotoSansArabic-ExtraCondensedLight.ttf
curl -s -O --output-dir lib/internal/NotoSans-arabic/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSansArabic/full/ttf/NotoSansArabic-ExtraCondensedMedium.ttf
curl -s -O --output-dir lib/internal/NotoSans-arabic/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSansArabic/full/ttf/NotoSansArabic-ExtraCondensedSemiBold.ttf
curl -s -O --output-dir lib/internal/NotoSans-arabic/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSansArabic/full/ttf/NotoSansArabic-ExtraCondensedThin.ttf
curl -s -O --output-dir lib/internal/NotoSans-arabic/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSansArabic/full/ttf/NotoSansArabic-ExtraCondensed.ttf
curl -s -O --output-dir lib/internal/NotoSans-arabic/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSansArabic/full/ttf/NotoSansArabic-ExtraLight.ttf
curl -s -O --output-dir lib/internal/NotoSans-arabic/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSansArabic/full/ttf/NotoSansArabic-Light.ttf
curl -s -O --output-dir lib/internal/NotoSans-arabic/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSansArabic/full/ttf/NotoSansArabic-Medium.ttf
curl -s -O --output-dir lib/internal/NotoSans-arabic/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSansArabic/full/ttf/NotoSansArabic-Regular.ttf
curl -s -O --output-dir lib/internal/NotoSans-arabic/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSansArabic/full/ttf/NotoSansArabic-SemiBold.ttf
curl -s -O --output-dir lib/internal/NotoSans-arabic/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSansArabic/full/ttf/NotoSansArabic-SemiCondensedBlack.ttf
curl -s -O --output-dir lib/internal/NotoSans-arabic/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSansArabic/full/ttf/NotoSansArabic-SemiCondensedBold.ttf
curl -s -O --output-dir lib/internal/NotoSans-arabic/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSansArabic/full/ttf/NotoSansArabic-SemiCondensedExtraBold.ttf
curl -s -O --output-dir lib/internal/NotoSans-arabic/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSansArabic/full/ttf/NotoSansArabic-SemiCondensedExtraLight.ttf
curl -s -O --output-dir lib/internal/NotoSans-arabic/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSansArabic/full/ttf/NotoSansArabic-SemiCondensedLight.ttf
curl -s -O --output-dir lib/internal/NotoSans-arabic/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSansArabic/full/ttf/NotoSansArabic-SemiCondensedMedium.ttf
curl -s -O --output-dir lib/internal/NotoSans-arabic/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSansArabic/full/ttf/NotoSansArabic-SemiCondensedSemiBold.ttf
curl -s -O --output-dir lib/internal/NotoSans-arabic/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSansArabic/full/ttf/NotoSansArabic-SemiCondensedThin.ttf
curl -s -O --output-dir lib/internal/NotoSans-arabic/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSansArabic/full/ttf/NotoSansArabic-SemiCondensed.ttf
curl -s -O --output-dir lib/internal/NotoSans-arabic/ --clobber https://raw.githubusercontent.com/notofonts/notofonts.github.io/refs/heads/main/fonts/NotoSansArabic/full/ttf/NotoSansArabic-Thin.ttf
